//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvironmentMaster
    {
        public int ID { get; set; }
        public string EnvironmentName { get; set; }
        public Nullable<int> ProcessTemplateID { get; set; }
        public bool IsCustom { get; set; }
        public Nullable<int> MemberID { get; set; }
        public bool Deactive { get; set; }
    
        public virtual ProcessTemplateMaster ProcessTemplateMaster { get; set; }
    }
}
