//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidMaster
    {
        public int ID { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string GUID { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public System.DateTime CreatedON { get; set; }
        public Nullable<System.DateTime> DeletedOn { get; set; }
    }
}
