//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberMaster()
        {
            this.GoalTargets = new HashSet<GoalTarget>();
            this.ProcessGoalMappings = new HashSet<ProcessGoalMapping>();
            this.TransactionMasters = new HashSet<TransactionMaster>();
            this.TransactionMasters1 = new HashSet<TransactionMaster>();
        }
    
        public int ID { get; set; }
        public string GUID { get; set; }
        public int MemberID { get; set; }
        public Nullable<int> WebsiteID { get; set; }
        public string MemberUserName { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string MemberType { get; set; }
        public string HomeAddress1 { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string EmployeeName { get; set; }
        public string MemberSuspended { get; set; }
        public bool IsYBpaymentCompleted { get; set; }
        public bool IsYBStepsCompleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalTarget> GoalTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessGoalMapping> ProcessGoalMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMaster> TransactionMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMaster> TransactionMasters1 { get; set; }
    }
}
