//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessTemplateMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessTemplateMaster()
        {
            this.EnvironmentMasters = new HashSet<EnvironmentMaster>();
            this.ProcessGoalMappings = new HashSet<ProcessGoalMapping>();
            this.ProcessTemplateSteps = new HashSet<ProcessTemplateStep>();
        }
    
        public int ID { get; set; }
        public string ProcessTemplateName { get; set; }
        public int Steps { get; set; }
        public bool IsCustom { get; set; }
        public Nullable<int> EnvironmentID { get; set; }
        public bool Deactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnvironmentMaster> EnvironmentMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessGoalMapping> ProcessGoalMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessTemplateStep> ProcessTemplateSteps { get; set; }
    }
}
