//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionMaster()
        {
            this.AnswerMasters = new HashSet<AnswerMaster>();
            this.TransactionMasters = new HashSet<TransactionMaster>();
        }
    
        public int ID { get; set; }
        public string Introduction { get; set; }
        public string Question { get; set; }
        public bool Deactive { get; set; }
        public int QuestionOrder { get; set; }
        public int LevelID { get; set; }
        public string ViewName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerMaster> AnswerMasters { get; set; }
        public virtual LevelMaster LevelMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionMaster> TransactionMasters { get; set; }
    }
}
