//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlexRogoBeltApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionMaster
    {
        public long ID { get; set; }
        public int MemberID { get; set; }
        public int QuestionID { get; set; }
        public int AnswerID { get; set; }
        public string ControlValue { get; set; }
        public bool Deactive { get; set; }
    
        public virtual AnswerMaster AnswerMaster { get; set; }
        public virtual MemberMaster MemberMaster { get; set; }
        public virtual QuestionMaster QuestionMaster { get; set; }
    }
}
